### ISSUE TITLE
OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#107]
I just triggered the following bug.

- Installed Widevine CDM over existing/working installation (this crashed due to #106)
- Due to the crash the image was not unmounted!
- After restart of Kodi, performed a new installation
- The new installation downloaded and mounted the image again over the existing mountpoint
- After installation the cleanup phase removes everything from the temporary directory
- This fails because this (still) mounted directory is read-only

Every successive installation will detect a Widevine update, which fails for the same reason.
(A reboot fixes this)

The solution is to check if the tmp/mnt is already a mounted file system, and if so to unmount.
Or when an issue occurs to perform the cleanup regardless.
Another fix is to first put Widevine CDM in place before cleanup, so that Widevine works, despite the error during cleanup.

```
2019-08-28 17:57:37.552 T:1707008880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 30] Read-only file system: '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/mnt/usr/local'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 253, in run
                                                plugin.run(argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 225, in play_id
                                                VRTPlayer(kodi).play(dict(video_id=video_id, publication_id=publication_id))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 287, in play
                                                self._kodi.play(stream, video.get('listitem'))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiwrapper.py", line 256, in play
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 934, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 892, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 822, in _check_widevine
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 683, in install_widevine
                                                return self._install_widevine_arm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 658, in _install_widevine_arm
                                                self._cleanup()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 869, in _cleanup
                                                shutil.rmtree(self._temp_path())
                                              File "/usr/lib/python2.7/shutil.py", line 261, in rmtree
                                              File "/usr/lib/python2.7/shutil.py", line 261, in rmtree
                                              File "/usr/lib/python2.7/shutil.py", line 261, in rmtree
                                              File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
                                              File "/usr/lib/python2.7/shutil.py", line 268, in rmtree
                                            OSError: [Errno 30] Read-only file system: '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/mnt/usr/local'
                                            -->End of Python script error report<--
```

**Comment by michaelarnauts** [comment]
Hmm. IMO the crash of #106 should be caught and the unmount should be done instead of checking on a new install.

**Comment by dagwieers** [comment]
@michaelarnauts Kodi segfaults/SIGBUSes, there's no recovering from that.

**Comment by michaelarnauts** [comment]
Ow, that's bad...
