### ISSUE TITLE
Unicode issue on Python 3

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#116]
Integration tests of the ARM installation procedure on Python 3 revealed another unicode issue:
```traceback
======================================================================
ERROR: test_check_inputstream_mpd_again (test.test_ishelper_lin_arm.LinuxARMTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/test/test_ishelper_lin_arm.py", line 28, in test_check_inputstream_mpd_again
    is_installed = is_helper.check_inputstream()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 947, in check_inputstream
    return self._check_drm()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 901, in _check_drm
    return self.install_widevine()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 686, in install_widevine
    return self._install_widevine_arm()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 613, in _install_widevine_arm
    localize(30006, diskspace=self._sizeof_fmt(required_diskspace))) and self._widevine_eula():
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 763, in _widevine_eula
    eula = f.read().strip().replace('\n', ' ')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by dagwieers** [comment]
This currently blocks #115

**Comment by mediaminister** [comment]
Just add `.decode()`
`eula = f.read().decode().strip().replace('\n', ' ')` should fix this.
