### ISSUE TITLE
libwidevinecdm.so lost execute permission

### ISSUE THREAD

**Issue by ZefQ** [emilsvennesson/script.module.inputstreamhelper#12]
First of, thanks for your awesome plugins.

I don't know if this is the right repo for this but, today i got a popup saying that i needed to update widevine to watch content from c-more. After letting the update complete I was unable to start the playback. Apparently libwidevinecdm.so did not get execution permission. (The log is for viaplay but it was the same for c-more 😄 )

```
19:20:55.917 T:956531600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'subprocess.CalledProcessError'>
    Error Contents: Command '['ldd', '/storage/.kodi/cdm/libwidevinecdm.so']' returned non-zero exit status 1
    Traceback (most recent call last):
    File "/storage/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
    addon.run()
    File "/storage/.kodi/addons/plugin.video.viaplay/addon.py", line 18, in run
    router(sys.argv[2][1:])  # trim the leading '?' from the plugin call paramstring
    File "/storage/.kodi/addons/plugin.video.viaplay/addon.py", line 474, in router
    helper.play(guid=params.get('guid'), url=params.get('url'))
```

I fixed the permission and playback worked again.
```
LibreELEC:~ # ldd /storage/.kodi/cdm/libwidevinecdm.so
ldd: $warning: you do not have execution permission for `/storage/.kodi/cdm/libwidevinecdm.so'
/usr/bin/ldd: eval: line 1: /storage/.kodi/cdm/libwidevinecdm.so: Permission denied
LibreELEC:~ # chmod +x /storage/.kodi/cdm/libwidevinecdm.so
LibreELEC:~ # ldd /storage/.kodi/cdm/libwidevinecdm.so
	linux-vdso.so.1 (0x7eec2000)
	/usr/lib/libarmmem.so (0x76f7a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76f51000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x76e0b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x76df8000)
	librt.so.1 => /usr/lib/librt.so.1 (0x76de1000)
	libnss3.so => /usr/lib/libnss3.so (0x76cf0000)
	libnssutil3.so => /usr/lib/libnssutil3.so (0x76cc0000)
	libnspr4.so => /usr/lib/libnspr4.so (0x76c8d000)
	libm.so.6 => /usr/lib/libm.so.6 (0x76c0e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x76be1000)
	libc.so.6 => /usr/lib/libc.so.6 (0x76aaa000)
	/lib/ld-linux-armhf.so.3 (0x76f90000)
	libplc4.so => /usr/lib/libplc4.so (0x76fb5000)
	libplds4.so => /usr/lib/libplds4.so (0x76fb1000)
```

**Comment by emilsvennesson** [comment]
Hi! I'm glad you're enjoying the add-ons. :-)

This was fixed earlier today (https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/105a9f92f7585b46faeafa415777b0ecfdae0100, https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/11). A new version has been pushed out with the fix included has been pushed out and should hit the official repository soon.
