### ISSUE TITLE
InputStream Helper API methods crash if InputStream Adaptive is not installed

### ISSUE THREAD

**Issue by mediaminister** [emilsvennesson/script.module.inputstreamhelper#131]
It's possible to install InputStream Helper and call API methods when InputStream Adaptive add-on is not installed or disabled, this causes a crash.
Before executing an API method, we should check if InputStream Adaptive add-on is installed/enabled and try to enable or install it automatically.

Debug log:
```
2019-08-30 23:20:35.811 T:3976   DEBUG: [script.module.inputstreamhelper][routing] Dispatching to 'widevine_remove', args: {}
2019-08-30 23:20:35.812 T:3976   DEBUG: [script.module.inputstreamhelper-0.3.5]: Platform information: uname_result(system='Windows', node='DESKTOP-LSHI51P', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
2019-08-30 23:20:35.816 T:3976   ERROR: EXCEPTION: Unknown addon id 'inputstream.adaptive'.
2019-08-30 23:20:35.878 T:3976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'RuntimeError'>
                                            Error Contents: Unknown addon id 'inputstream.adaptive'.
                                            Traceback (most recent call last):
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\addon.py", line 48, in <module>
                                                plugin.run(sys.argv)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\addon.py", line 44, in widevine_remove
                                                Helper('mpd', drm='widevine').remove_widevine()
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 699, in remove_widevine
                                                widevinecdm = self._widevine_path()
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 181, in _widevine_path
                                                widevine_path = os.path.join(cls._ia_cdm_path(), widevine_cdm_filename)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 154, in _ia_cdm_path
                                                addon = xbmcaddon.Addon('inputstream.adaptive')
                                            RuntimeError: Unknown addon id 'inputstream.adaptive'.
                                            -->End of Python script error report<--

```

**Comment by dagwieers** [comment]
Not sure if we can fix this before v0.4.0 release. And this is equally true for **inputstream.rtmp**.

**Comment by mediaminister** [comment]
Fixing this is not urgent. Should be fixed before v1.0 though.

**Comment by mediaminister** [comment]
When executing API methods we should also check if Kodi 18 or higher is used, on Kodi 17 `remove_widevine` crashes and `install_widevine` gives a nice error message "Kodi 18 or higher is required.

**Comment by dagwieers** [comment]
Removing should not really be a problem on Kodi v17.
If it is just a file operation.

**Comment by mediaminister** [comment]
I'm currently looking into this and I came to the conclusion that installing Widevine CDM alone doesn't make any sense. To use Widevine CDM, a user **always** need Kodi 18 and InputStream Adaptive add-on.

So, we must always check these dependencies before installing Widevine CDM and this is already implemented in the main function `check_inputstream`. In fact `install_widevine` is already duplicating existing functionality.

We must reconsider what functionality the API must contain and how we present this functionality to the user.

Any ideas a
