### ISSUE TITLE
Error: Destination path 'special://masterprofile/.../temp' already exists

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#186]
The integration tests now fail on this on my system, so definitely something to avoid before v0.4.3 release.
```
======================================================================
ERROR: test_check_inputstream_hls_again (test.test_ishelper_linux_arm.LinuxARMTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dag/home-made/script.module.inputstreamhelper/test/test_ishelper_linux_arm.py", line 32, in test_check_inputstream_hls_again
    is_installed = is_helper.check_inputstream()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 937, in check_inputstream
    return self._check_drm()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 895, in _check_drm
    return self.install_widevine()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 676, in install_widevine
    return self._install_widevine_arm()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 601, in _install_widevine_arm
    self._update_temp_path(Dialog().browseSingle(3, localize(30909), 'files'))  # Temporary path
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 201, in _update_temp_path
    shutil.move(old_temp_path, new_temp_path)
  File "/usr/lib64/python2.7/shutil.py", line 291, in move
    raise Error, "Destination path '%s' already exists" % real_dst
Error: Destination path 'special://masterprofile/addon_data/script.module.inputstreamhelper/temp' already exists

======================================================================
ERROR: test_check_inputstream_mpd (test.test_ishelper_linux_arm.LinuxARMTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dag/home-made/script.module.inputstreamhelper/test/test_ishelper_linux_arm.py", line 25, in test_check_inputstream_mpd
    is_installed = is_helper.check_inputstream()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 937, in check_inputstream
    return self._check_drm()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 895, in _check_drm
    return self.install_widevine()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 676, in install_widevine
    return self._install_widevine_arm()
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 601, in _install_widevine_arm
    self._update_temp_path(Dialog().browseSingle(3, localize(30909), 'files'))  # Temporary path
  File "/home/dag/home-made/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 201, in _update_temp_path
    shutil.move(old_temp_path, new_temp_path)
  File "/usr/lib64/python2.7/shutil.py", line 291, in move
    raise Error, "Destination path '%s' already exists" % real_dst
Error: Destination path 'special://masterprofile/addon_data/script.module.inputstreamhelper/temp' already exists
```

**Comment by dagwieers** [comment]
I guess if the user selects the same path that already existed, we should be moving.

**Comment by dagwieers** [comment]
It is more complex, the path is untranslated, but even when translated it fails with the same error.
And the paths are not exactly the same, the old path had */temp* appended :-/
