### ISSUE TITLE
Non-ascii chars in proxy settings cannot be decoded

### ISSUE THREAD

**Issue by sikjo** [emilsvennesson/script.module.inputstreamhelper#244]
If the proxy settings has a username or password that contain non-ascii characters, parsing will fail. This can be seen when trying to play a clip on Netflix as the following error message is presented:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)`

How to reproduce
1. Activate the proxy in Kodi settings.
2. Add a non-ascii character as user name (like £, ö, or any other national characters).
3. Attempting to play a clip in Netflix will now fail.
4. Change the username to pure ascii.
5. Playing will work again.

I am only attaching the stack trace since it's so easy to reproduce the error. If you wish to have the full debug log, let me know.

```
2020-01-03 20:00:42.770 T:3163128544   ERROR: [plugin.video.netflix (9)] Traceback (most recent call last):
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 162, in run
       route([part for part in g.PATH.split('/') if part])
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 31, in lazy_login_wrapper
       return func(*args, **kwargs)
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 55, in route
       play(videoid=pathitems[1:])
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 294, in wrapper
       return func(*args, **kwargs)
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 264, in timing_wrapper
       return func(*args, **kwargs)
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 65, in play
       list_item = get_inputstream_listitem(videoid)
     File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 109, in get_inputstream_listitem
       is_helper = inputstreamhelper.Helper('mpd', drm='widevine')
     File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 81, in __init__
       install_opener(build_opener(ProxyHandler(get_proxies())))
     File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 97, in get_proxies
       httpproxypassword = get_global_setting('network.httpproxypassword')
     File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 66, in get_global_setting
       result = execute_jsonrpc(dict(jsonrpc='2.0', id=1, method='Settings.GetSettingValue', params=dict(setting='%s' % setting)))
     File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 128, in execute_jsonrpc
       log('jsonrpc response: {response}', response=response)
     File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 134, in log
       xbmc.log(msg=from_unicode('[{addon}]: {msg}'.format(addon=get_addon_info('id'), msg=msg.format(**kwargs))), level=xbmc.LOGDEBUG)
   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)
```

Operating System:  OSMC 2019-11-1 on Vero 4k
Inputstreamhelper addon version: 0.4.3
Netflix addon version: 0.16.1

**Comment by dagwieers** [comment]
Could you try to install the master branch instead?
Because I think it is no affected by this issue.

Download this ZIP file: https://github.com/emilsvennesson/script.module.inputstreamhelper/archive/master.zip
And use **Install from ZIP** in the Add-on section.

**Comment by sikjo** [comment]
I did a quick test last night and you appear to be right.

On the first run I did get the error though but I believe it was a caching issue. Unfortunately, I forgot to save the logs so I will revert to 0.4.3 and redo the tests later this week.

**Comment by sikjo** [comment]
Ok, after further tests I am confident that the issue is fixed in the master branch.

Thank you for your attention.
