### ISSUE TITLE
_up date_widevine fails with "TypeError: function missing required argument 'line1' (pos 2)"

### ISSUE THREAD

**Issue by raoulbhatia** [emilsvennesson/script.module.inputstreamhelper#324]
_(Please let me know what details you need in addition)_

Running on LibreElec on RPi

* script.module.inputstreamhelper-0.4.5 matrix.1.zip
* LibreELEC (Milhouse): devel-20200129003814-#0128-g6a49b98 (RPi2.arm)
  * Starting Kodi (19.0-ALPHA1 Git:7684111). Platform: Linux ARM 32-bit
  * Using Release Kodi x32 build (version for Raspberry Pi)
  * Kodi compiled 2020-01-29 by GCC 9.2.0 for Linux ARM 32-bit version 5.4.13 (328717)
* Python 3.7.6

```
2020-04-23 22:01:15.367 T:1656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'TypeError'>
                                            Error Contents: function missing required argument 'line1' (pos 2)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 80, in EntryPoint
                                                PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(a
rgs.get('selbitrate', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 434, in PlayVideo
                                                playable = _IStreamPlayback(asin, name, streamtype, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 301, in _IStreamPlayback
                                                if not inputstream_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 401, in che
ck_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 353, in _ch
eck_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 313, in _ch
eck_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 283, in _up
date_widevine
                                                if yesno_dialog(localize(30040), localize(30033), nolabel=localize(30028), yeslabel=localize(30034)):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 124, in ye
sno_dialog
                                                return Dialog().yesno(heading=heading, message=message, nolabel=nolabel, yeslabel=yeslabel, autoclose=autoclos
e)
                                            TypeError: function missing required argument 'line1' (pos 2)
                                            -->End of Python script error report<--
```

**Comment by dagwieers** [comment]
The Kodi v19 interfaces have changed, and we have updated our add-on, but your version is too old.
I guess this is what you get when running a development version, you have to keep up with newer development if you want things to keep working. Sorry.
