### ISSUE TITLE
Error while installing Widevine update

### ISSUE THREAD

**Issue by AlCalzone** [emilsvennesson/script.module.inputstreamhelper#33]
This is a repost from https://github.com/Sandmann79/xbmc/issues/156 as I was told the error is related to this module

I tried to play videos using the Amazon VOD Kodi plugin, but I always get the message that a Widevine update is required. However, after accepting the EULA, the update crashes with the following error message:

```
20:19:11.561 T:1590670192 WARNING: CPythonInvoker(16, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
20:19:11.572 T:1939529744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=B015NZ83EG&mode=PlayVideo&adult=0&name=1+-+Pilot&trailer=0&selbitrate=0]
20:20:10.319 T:1590670192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 12] Cannot allocate memory
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 68, in EntryPoint
                                                PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 579, in PlayVideo
                                                playable = _IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 459, in _IStreamPlayback
                                                if not inputstream_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 763, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 741, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 655, in _check_widevine
                                                return self._install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 542, in _install_widevine
                                                return self._install_widevine_arm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 485, in _install_widevine_arm
                                                if not self._cmd_exists('fdisk') and not self._cmd_exists('parted'):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 164, in _cmd_exists
                                                return subprocess.call('type ' + cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
                                              File "/usr/lib/python2.7/subprocess.py", line 172, in call
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 938, in _execute_child
                                            OSError: [Errno 12] Cannot allocate memory
                                            -->End of Python script error report<--
20:20:10.486 T:1590670192 WARNING: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
20:20:10.499 T:1939529744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=B015X5GVZO&mode=PlayVideo&adult=0&name=2+-+A+Stray+Howl&trailer=0&selbitrate=0]
```

I'm using LibreElec 9 on a RPi 3 if that helps somehow.

**Comment by AlCalzone** [comment]
It took me a while to get back to this, but your comment helped.
The manual update of inputstreamhelper to the current master did the trick. Now it was able to download the image and is currently in the process of installing the update.

**Comment by AlCalzone** [comment]
Aaand its working. Thanks a lot!
