### ISSUE TITLE
Widevine - can't get it running on Windows 10

### ISSUE THREAD

**Issue by bugsyb** [emilsvennesson/script.module.inputstreamhelper#331]
Hi,

Seems like I'm hitting some problem with Widevine and Windows 10.
It claims that too old version has been found and asks to re-install which after EULA accept bombs out with following in logs (below).
.dll has been put into CDM folder manually to test but it didn't help either (4.10.1610.0)

Happy to install it manually for test. Feeling is that python tries to use hard-links which fail on Windows. It doesn't seem like it downloads latest version either.

Thanks for help.

```
2020-05-01 01:56:57.814 T:2288   ERROR: [script.module.inputstreamhelper] Widevine or Chrome OS recovery.conf is missing. Reinstall is required.
2020-05-01 01:57:00.496 T:2288  NOTICE: [script.module.inputstreamhelper] Recursively create directory 'C:\Users\localluser\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\temp'.
2020-05-01 01:57:00.496 T:2288  NOTICE: [script.module.inputstreamhelper] Create directory 'C:\Users\localluser\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\temp\mnt'.
2020-05-01 01:57:00.499 T:2288  NOTICE: [script.module.inputstreamhelper] Create directory 'C:\Users\localluser\AppData\Roaming\Kodi\cdm'.
2020-05-01 01:57:00.500 T:2288  NOTICE: Previous line repeats 1 times.
2020-05-01 01:57:00.500 T:2288  NOTICE: [script.module.inputstreamhelper] Recursively create directory 'C:\Users\localluser\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\temp'.
2020-05-01 01:57:03.775 T:2288  NOTICE: Previous line repeats 1 times.
2020-05-01 01:57:03.775 T:2288  NOTICE: [script.module.inputstreamhelper] Create directory 'C:\Users\localluser\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\backup'.
2020-05-01 01:57:03.966 T:2288  NOTICE: [script.module.inputstreamhelper] Recursively create directory 'C:\Users\localluser\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\backup\4.10.1582.2'.
2020-05-01 01:57:04.106 T:2288  NOTICE: [script.module.inputstreamhelper] Create directory 'C:\Users\localluser\AppData\Roaming\Kodi\userdata\addon_data\script.module.inputstreamhelper\backup'.
2020-05-01 01:57:04.108 T:2288  NOTICE: Previous line repeats 1 times.
2020-05-01 01:57:04.108 T:2288  NOTICE: [script.module.inputstreamhelper] Create directory 'C:\Users\localluser\AppData\Roaming\Kodi\cdm'.
2020-05-01 01:57:04.109 T:2288   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 62, in route
                                                play(videoid=pathitems[1:])
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\videoid.py", line 295, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\logging.py", line 148, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\player.py", line 82, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\navigation\player.py", line 163, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 306, in _check_widevine
                                                return self.install_widevine()
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 227, in install_widevine
                                                if self.install_and_finish(*result):
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 197, in install_and_finish
                                                install_cdm_from_backup(version)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\widevine\widevine.py", line 20, in install_cdm_from_backup
                                                hardlink(backup_fpath, install_fpath)
                                              File "C:\Users\localluser\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\utils.py", line 264, in hardlink
                                                from os import link
                                            ImportError: cannot import name link
```

**Comment by arvvoid** [comment]
I just made tmp zip until 0.4.7 is out for users affected by the issue, a user asked for support on the Kodi forum for Hbo go add-on that experienced this issue.

[NOTE TO USERS: Please note this is not an official release of this add-on and just a tmp fix until 0.4.7 is out]

Leia:
[script.module.inputstreamhelper-0.4.6-master-ddf7359.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4569802/script.module.inputstreamhelper-0.4.6-master-ddf7359.zip)

**Comment by bugsyb** [comment]
Thank you very much.

**Comment by dagwieers** [comment]
@arvvoid Users can also download the zip from any branch and install that.

This used to work fine for all Kodi releases until they broke Matrix in an backward-incompatible way. So for Matrix that no longer applies...
