### ISSUE TITLE
Error during Widevine extraction - Occured just today

### ISSUE THREAD

**Issue by fesarlis** [emilsvennesson/script.module.inputstreamhelper#335]
Over the last week I had no issue installing Netflix plugin. Just today I receive the following error. CastagnaIT suggested to report this here instead. I tried using the zip provied in #333, and also to use 0.45. Still no luck.
It was working fine (the extraction I mean) until yesterday. I am doing many installations for testing purposes.

Here is the log produced:

2020-05-01 07:46:04.420 T:3664741232   ERROR: [plugin.video.netflix (2)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 182, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 57, in route
                                                play(videoid=pathitems[1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 294, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 133, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 72, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 144, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 362, in _check_drm
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 240, in install_widevine_arm
                                                extract_widevine_from_img(os.path.join(backup_path, arm_device['version']))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img
                                                for root, _, files in os.walk(mnt_path()):
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 73, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)

**Comment by horstle** [comment]
Same as #333
