### ISSUE TITLE
Error while extracting decoder

### ISSUE THREAD

**Issue by cyber-jpg** [emilsvennesson/script.module.inputstreamhelper#342]
2020-05-03 07:13:43.247 T:2420106096  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-03 07:13:43.247 T:2420106096  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt'.
2020-05-03 07:13:43.261 T:2420106096  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/cdm'.
2020-05-03 07:13:43.264 T:2420106096  NOTICE: Previous line repeats 1 times.
2020-05-03 07:13:43.264 T:2420106096 WARNING: [script.module.inputstreamhelper] Widevine CDM is not installed.
2020-05-03 07:13:43.266 T:2420106096  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/cdm'.
2020-05-03 07:13:43.267 T:2420106096  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-03 07:13:43.926 T:2420106096  NOTICE: Previous line repeats 1 times.
2020-05-03 07:13:43.926 T:2420106096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: u'/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/4.10.1582.2-mac-x64.zip'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 217, in install_widevine
                                                if not widevine_eula():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 39, in widevine_eula
                                                downloaded = http_download(url, message=localize(30025))  # Acquiring EULA
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 92, in http_download
                                                with open(download_path, 'wb') as image:
                                            IOError: [Errno 2] No such file or directory: u'/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/4.10.1582.2-mac-x64.zip'
                                            -->End of Python script error report<--

**Comment by horstle** [comment]
Should be fixed: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/334/files#diff-68cc89a423b48fc3f74979a0ea3b7dc2R93
