### ISSUE TITLE
Extraction failing with "Error -3 while decompressing: invalid distance code"

### ISSUE THREAD

**Issue by thiago-dev** [emilsvennesson/script.module.inputstreamhelper#404]
**Problem:**
The extraction of Widevine fails with _Error -3 while decompressing: invalid distance code_

**System:**
Rpi3
LibreELEC (official): 9.2.4, kernel: Linux ARM 32-bit version 4.19.127
Kodi (18.8 (18.8.0) Git:newclock5_18.8-Leia)
script.module.inputstreamhelper v0.5.1 
[Full Debug Log](https://paste.kodi.tv/cisatenapa.kodi)

```
2020-10-14 18:41:28.497 T:1386775424 DEBUG: CPythonInvoker(12, /storage/.kodi/addons/script.module.inputstreamhelper/default.py): start processing

2020-10-14 18:41:28.527 T:1386775424 DEBUG: -->Python Interpreter Initialized<--

2020-10-14 18:41:28.527 T:1386775424 DEBUG: CPythonInvoker(12, /storage/.kodi/addons/script.module.inputstreamhelper/default.py): the source file to load is "/storage/.kodi/addons/script.module.inputstreamhelper/default.py"

2020-10-14 18:41:28.527 T:1386775424 DEBUG: CPythonInvoker(12, /storage/.kodi/addons/script.module.inputstreamhelper/default.py): setting the Python path to /storage/.kodi/addons/script.module.inputstreamhelper:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0

2020-10-14 18:41:28.527 T:1386775424 DEBUG: CPythonInvoker(12, /storage/.kodi/addons/script.module.inputstreamhelper/default.py): entering source directory /storage/.kodi/addons/script.module.inputstreamhelper

2020-10-14 18:41:28.528 T:1386775424 DEBUG: CPythonInvoker(12, /storage/.kodi/addons/script.module.inputstreamhelper/default.py): instantiating addon using automatically obtained id of "script.module.inputstreamhelper" dependent on version 2.25.0 of the xbmc.python api

2020-10-14 18:41:28.696 T:1386775424 DEBUG: [script.module.inputstreamhelper] Platform information: ('Linux', 'LibreELEC', '4.19.127', '#1 SMP Wed Jul 29 15:27:14 EDT 2020', 'armv7l', '')

2020-10-14 18:41:28.698 T:1386775424 DEBUG: CAddonSettings[script.module.inputstreamhelper]: loading setting definitions

2020-10-14 18:41:28.698 T:1386775424 DEBUG: CAddonSettings[script.module.inputstreamhelper]: trying to load setting definitions from old format...

2020-10-14 18:41:28.700 T:1386775424 DEBUG: CAddonSettings[script.module.inputstreamhelper]: loading setting values

2020-10-14 18:41:28.748 T:1386775424 DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions

2020-10-14 18:41:28.753 T:1386775424 DEBUG: Previous line repeats 1 times.

2020-10-14 18:41:28.753 T:1386775424 WARNING: [script.module.inputstreamhelper] Widevine CDM is not installed.

2020-10-14 18:41:28.754 T:1386775424 DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions

2020-10-14 18:41:28.794 T:1386775424 DEBUG: [script.module.inputstreamhelper] Found system architecture arm

2020-10-14 18:41:28.810 T:1386775424 DEBUG: [script.module.inputstreamhelper] Request URL: https://dl.google.com/widevine-cdm/versions.txt

2020-10-14 18:41:29.006 T:1386775424 DEBUG: [script.module.inputstreamhelper] Response code: 200

2020-10-14 18:41:29.020 T:1386775424 DEBUG: [script.module.inputstreamhelper] Acquiring Widevine EULA from x86 files.

2020-10-14 18:41:29.021 T:1386775424 DEBUG: [script.module.inputstreamhelper] Request URL: https://dl.google.com/widevine-cdm/4.10.1582.2-mac-x64.zip

2020-10-14 18:41:29.181 T:1386775424 DEBUG: [script.module.inputstreamhelper] Response code: 200

2020-10-14 18:41:29.183 T:1386775424 NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.

2020-10-14 18:41:29.213 T:1937276944 DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------

2020-10-14 18:41:29.727 T:1386775424 DEBUG: [script.module.inputstreamhelper] Stored /storage/.kodi/userdata/addondata/script.module.inputstreamhelper/temp/4.10.1582.2-mac-x64.zip in downloadpath

2020-10-14 18:41:29.779 T:1937276944 DEBUG: ------ Window Init (DialogConfirm.xml) ------

2020-10-14 18:41:29.779 T:1937276944 INFO: Loading skin file: DialogConfirm.xml, load type: KEEPINMEMORY

2020-10-14 18:41:29.898 T:1937276944 DEBUG: ------ Window Deinit (DialogExtendedProgressBar.xml) ------

2020-10-14 18:41:30.836 T:1860170624 DEBUG: LIRC: - NEW 69 0 KEYLEFT devinput (KEYLEFT)

2020-10-14 18:41:30.846 T:1937276944 DEBUG: HandleKey: 169 (0xa9, obc86) pressed, action is Left

2020-10-14 18:41:31.489 T:1860170624 DEBUG: LIRC: - NEW 160 0 KEYOK devinput (KEYOK)

2020-10-14 18:41:31.496 T:1937276944 DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select

2020-10-14 18:41:31.698 T:1937276944 DEBUG: ------ Window Deinit (DialogConfirm.xml) ------

2020-10-14 18:41:31.747 T:1386775424 DEBUG: [script.module.inputstreamhelper] Request URL: https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.json

2020-10-14 18:41:31.901 T:1386775424 DEBUG: [script.module.inputstreamhelper] Response code: 200

2020-10-14 18:41:32.018 T:1386775424 DEBUG: [script.module.inputstreamhelper] Find best ARM image to use from the Chrome OS recovery.json

2020-10-14 18:41:32.025 T:1386775424 DEBUG: [script.module.inputstreamhelper] ELM (3352543009) is smaller than BOB (3355083716)

2020-10-14 18:41:32.028 T:1386775424 DEBUG: [script.module.inputstreamhelper] EXPRESSO (2992851306) is smaller than ELM (3352543009)

2020-10-14 18:41:32.041 T:1386775424 DEBUG: [script.module.inputstreamhelper] KITTY (2951370661) is smaller than EXPRESSO (2992851306)

2020-10-14 18:41:32.064 T:1386775424 DEBUG: [script.module.inputstreamhelper] MICKEY (2941183176) is smaller than KITTY (2951370661)

2020-10-14 18:41:32.096 T:1937276944 DEBUG: ------ Window Init (DialogConfirm.xml) ------

2020-10-14 18:41:33.282 T:1860170624 DEBUG: LIRC: - NEW 69 0 KEYLEFT devinput (KEYLEFT)

2020-10-14 18:41:33.306 T:1937276944 DEBUG: HandleKey: 169 (0xa9, obc86) pressed, action is Left

2020-10-14 18:41:33.890 T:1860170624 DEBUG: LIRC: - NEW 160 0 KEYOK devinput (KEYOK)

2020-10-14 18:41:33.929 T:1937276944 DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select

2020-10-14 18:41:34.138 T:1937276944 DEBUG: ------ Window Deinit (DialogConfirm.xml) ------

2020-10-14 18:41:34.180 T:1386775424 DEBUG: [script.module.inputstreamhelper] Request URL: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos13310.93.0veyron-mickeyrecoverystable-channel_mickey-mp-v2.bin.zip

2020-10-14 18:41:34.354 T:1386775424 DEBUG: [script.module.inputstreamhelper] Response code: 200

2020-10-14 18:41:34.356 T:1386775424 DEBUG: DialogProgress::Open called

2020-10-14 18:41:34.356 T:1386775424 DEBUG: ------ Window Init (DialogConfirm.xml) ------

2020-10-14 18:41:34.356 T:1386775424 INFO: Loading skin file: DialogConfirm.xml, load type: KEEPINMEMORY

2020-10-14 18:41:51.105 T:1638916992 DEBUG: Thread JobWorker 1638916992 terminating (autodelete)

2020-10-14 18:41:51.106 T:1807721344 DEBUG: Thread JobWorker 1807721344 terminating (autodelete)

2020-10-14 18:41:51.106 T:1565135744 DEBUG: Thread JobWorker 1565135744 terminating (autodelete)

2020-10-14 18:41:51.594 T:1596953472 DEBUG: Thread JobWorker 1596953472 terminating (autodelete)

2020-10-14 18:42:35.009 T:1908347776 DEBUG: CAESinkPi:Drain delay:99ms now:0ms

2020-10-14 18:42:45.013 T:1908347776 DEBUG: CAESinkPi:Deinitialize

2020-10-14 18:42:45.013 T:1908347776 DEBUG: CAESinkPi:SetAudioProps hdmistreamchannels 0 hdmichannelmap 00000000

2020-10-14 18:42:45.019 T:1908347776 DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_render handle 0x700030c0

2020-10-14 18:43:00.013 T:1386775424 DEBUG: [script.module.inputstreamhelper] Stored /storage/.kodi/userdata/addondata/script.module.inputstreamhelper/temp/chromeos13310.93.0veyron-mickeyrecoverystable-channelmickey-mp-v2.bin.zip in download_path

2020-10-14 18:43:00.217 T:1937276944 DEBUG: ------ Window Deinit (DialogConfirm.xml) ------

2020-10-14 18:43:00.230 T:1386775424 DEBUG: DialogProgress::Open called

2020-10-14 18:43:00.230 T:1386775424 DEBUG: ------ Window Init (DialogConfirm.xml) ------

2020-10-14 18:44:58.305 T:1386775424 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

                                        Error Type: <class 'zlib.error'>

                                        Error Contents: Error -3 while decompressing: invalid distance code

                                        Traceback (most recent call last):

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>

                                            run(sys.argv)

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run

                                            widevine_install()

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install

                                            Helper('mpd', drm='widevine').install_widevine()

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/**init**.py", line 34, in clean*before*after

                                            result = func(self, *args,* \*kwargs)

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/**init**.py", line 224, in install_widevine

                                            result = install*widevine*arm(backup_path())

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 160, in install*widevine*arm

                                            progress=progress)

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm*chromeos.py", line 110, in extract*file

                                            inode*dict,*  = self.inode*table(inode*pos)

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm*chromeos.py", line 179, in inode*table

                                            self.seek*stream(inode*pos)

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm*chromeos.py", line 249, in seek*stream

                                            self.read_stream(chunksize)

                                          File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm*chromeos.py", line 258, in read*stream

                                            return self.bstream[0].read(num*of*bytes)

                                          File "/usr/lib/python2.7/zipfile.py", line 655, in read

                                          File "/usr/lib/python2.7/zipfile.py", line 707, in read1

                                        error: Error -3 while decompressing: invalid distance code

                                        -->End of Python script error report<--
```

**Already tried:**
- Changing download directory (from internal SD-Card storage to external USB)
- Using LAN based connection instead of WLAN

**Comment by horstle** [comment]
Your system is doing something strange with underscores. E.g. the line
```
DEBUG: [script.module.inputstreamhelper] Stored /storage/.kodi/userdata/addondata/script.module.inputstreamhelper/temp/chromeos13310.93.0veyron-mickeyrecoverystable-channelmickey-mp-v2.bin.zip in download_path
```
should actually end on `chromeos_13310.93.0_veyron-mickey_recovery_stable-channel_mickey-mp-v2.bin.zip`
Similarly
```
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/**init**.py", line 34, in clean*before*after
```
should actually have `__init__.py` and `clean_before_after` in it.

But even though the url is logged wrong in
```
DEBUG: [script.module.inputstreamhelper] Request URL: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos13310.93.0veyron-mickeyrecoverystable-channel_mickey-mp-v2.bin.zip
```
it still seems to download the file correctly, so I'm not completely sure if this is where the problem is coming from.

I could investigate further maybe this evening or on the weekend, but I think the problem is in your system.

**Comment by thiago-dev** [comment]
Thanks for your reply.

I didn't notice the differences with the underscores, but it appears (after checking the filesystem) that they are actually stored with correct endings. It must be a formatting issue brought about by copy-pasting unformatted text from notepad into different markdown applications.

But after retrying to install widevine today and experiencing a different error in about the same phase, it wouldn't be surprising if the problem comes from other parts of my local system than the inputstreamhelper module. Currently I have no clue what could cause this sort of problem, because the system itself is beside a "few" installed addons "nearly" unmodified. 

What can I do or which more informations (logs etc.) do you need to speed up your investigations?



[Todays full Debug-Log](https://paste.kodi.tv/eyasepited.kodi)
```
2020-10-16 22:50:16.538 T:1522439040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Expecting property name enclosed in double quotes: line 3880 column 64 (char 143393)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 224, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 127, in install_widevine_arm
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 122, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
                                            ValueError: Expecting property name enclosed in double quotes: line 3880 column 64 (char 143393)
                                            -->End of Python script error report<--
```

```
2020-10-16 22:59:47.999 T:1522439040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: Bad CRC-32 for file 'chromeos_13310.93.0_veyron-mickey_recovery_stable-channel_mickey-mp-v2.bin'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 224, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 170, in install_widevine_arm
                                                return install_wv_arm_legacy(backup_path)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in install_wv_arm_legacy
                                                chunk = member.read(chunksize)
                                              File "/usr/lib/python2.7/zipfile.py", line 655, in read
                                              File "/usr/lib/python2.7/zipfile.py", line 715, in read1
                                              File "/usr/lib/python2.7/zipfile.py", line 670, in _update_crc
                                            BadZipfile: Bad CRC-32 for file 'chromeos_13310.93.0_veyron-mickey_recovery_stable-channel_mickey-mp-v2.bin'
                                            -->End of Python script error report<--
```

**Comment by horstle** [comment]
No idea about the json error, but the others could be explained by a corrupted file. Could you maybe try a different SD card? Alternatively you could connect a USB drive and specify that as "custom temporary path" on the settings page of inputstreamhelper. If it runs fine, I'd guess your SD card is failing.

**Comment by thiago-dev** [comment]
A different SD card worked out straight away.

Thanks.
