### ISSUE TITLE
Update of widevine failing

### ISSUE THREAD

**Issue by neunzehnachtneun** [emilsvennesson/script.module.inputstreamhelper#444]
InputStream Helper is saying an update of widevine cdm is necessary. If I agree, it fails with the following error.

Do you have any ideas or suggestions? Thanks!

```
2021-05-29 17:02:55.874 T:1446495104   ERROR: [script.module.inputstreamhelper] Widevine or Chrome OS recovery.json is missing. Reinstall is required.
2021-05-29 17:02:58.218 T:1446495104  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.modul>
2021-05-29 17:03:06.986 T:1446495104   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 157, in get_inputstr>
                                                inputstream_ready = is_helper.check_inputstream()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 410, in ch>
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 362, in _c>
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 310, in _c>
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in cle>
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 221, in in>
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 145, i>
                                                if yesno_dialog(localize(30066), localize(30067, os=kodi_os())):  # Your operating system probably doesn't su>
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 72, in ko>
                                                while ' (kernel: ' not in xbmc.getInfoLabel('System.OSVersionInfo') and count < 10:
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

**Comment by mediaminister** [comment]
Which OS and version?

Please test and report if these test packages work:
Kodi 19 Matrix: [script.module.inputstreamhelper-0.5.4+matrix.1-unicode-0ff63b0.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/6569294/script.module.inputstreamhelper-0.5.4%2Bmatrix.1-unicode-0ff63b0.zip)
Kodi 18 Leia: [script.module.inputstreamhelper-0.5.4-unicode-0ff63b0.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/6569295/script.module.inputstreamhelper-0.5.4-unicode-0ff63b0.zip)

**Comment by neunzehnachtneun** [comment]
Version is release 0.5.4, a downgrade to 0.5.3 seems to be successful so far. I will check your update soon.
I am using Libreelec with kodi leia.

Thanks a lot!

**Comment by neunzehnachtneun** [comment]
Yes, thanks. It is working again!

Cheers!
