### ISSUE TITLE
SSL Certificate error on ChromeOS-Recovery URL

### ISSUE THREAD

**Issue by ashleysommer** [emilsvennesson/script.module.inputstreamhelper#494]
When checking for a new version of WideVine, or when attempting to a video from Netflix

```
 [script.module.inputstreamhelper] Download failed with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
2022-03-07 18:06:46.688 T:4996     INFO <general>: Skipped 1 duplicate messages..
2022-03-07 18:06:46.688 T:4996    ERROR <general>: [plugin.video.netflix (4)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 104, in get_inputstream_listitem
                                                       inputstream_ready = is_helper.check_inputstream()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                       return self._check_drm()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                       return self._check_widevine()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                       self._update_widevine()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                       latest_version = latest_widevine_version()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                       devices = chromeos_config()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                       return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                                     File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
                                                   TypeError: the JSON object must be str, bytes or bytearray, not NoneType

```

**Comment by ashleysommer** [comment]
Ok, turns out there was something super wrong with my CA certs cache on CoreElec. The problem persisted across two reboots, but cleared itself on the third reboot.
Seems like I might need a new SD card if this persists.
