### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#510]
We are seeing this issue when remotely debugging playback issues in the VRT.NU add-on.
```
2022-03-30 22:44:24.123 T:1551946624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                plugin.run(argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 287, in play_id
                                                VRTPlayer().play(dict(video_id=video_id, publication_id=publication_id))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 400, in play
                                                play(stream, video.get('listitem'))
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 315, in play
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
```

This issue occurs on a Raspberry Pi 3 using LibreElec v9.2.8 and Kodi v18.9.0.(Python2) during playback, but it also happens when trying to reinstall Widevine CDM.

```
2022-03-30 22:36:00.928 T:1799328640  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.
2022-03-30 22:36:07.452 T:1799328640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 221, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 69, in install_widevine_arm
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by horstle** [comment]
Honestly?? #504 #503 #502 #500 #495

**Comment by horstle** [comment]
And, not to forget: https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.5.9

**Comment by dagwieers** [comment]
@horstle It is very simple, if you close an issue because it is fixed (but not released), people don't see the issue when they have an issue and so to open a new issue.

That is why you should keep an issue open, until it is fixed _and_ released in the repository. As long as it is not available, it is not fixed for end-users.

I honestly did not see a report of this issue when I troubleshooted this issue and my brother was using the latest release. So it is normal I open a new issue for it.

If people keep reporting the same issue, maybe they don't find the existing issue, or did not recognize it as such.
