### ISSUE TITLE
Widevine on x86 LIbreelec Kodi 19.4 cant install

### ISSUE THREAD

**Issue by Biomecanoid** [emilsvennesson/script.module.inputstreamhelper#521]
Hello,

I have 2 Libreelec x86 boxes at home. Today I realized that on one of my boxes Widevine got messed up and won't even re-install.

I have tried to read all threads related to Widevine but I could not find a remedy to my problem.

It seems that Libreelec is looking for Widevine in the wrong path /usr/lib/kodi/addons instead of /storage/.kodi/cmd

https://i.postimg.cc/44FK3mjN/20220821-000046.jpg

https://i.postimg.cc/X7GrBn0K/IMG-20220821-004641.jpg

Here is an extract of the log file

2022-08-20 23:20:22.688 T:8791 INFO <general>: Skipped 1 duplicate messages..

2022-08-20 23:20:22.688 T:8791 ERROR <general>: [script.module.inputstreamhelper] Widevine CDM is not installed.

2022-08-20 23:20:25.050 T:8791 INFO <general>: Skipped 1 duplicate messages..

2022-08-20 23:20:25.050 T:8791 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <class 'OSError'>

Error Contents: [Errno 30] Read-only file system: 'peripheral.joystick.so'

Traceback (most recent call last):

File "/storage/.kodi/addons/plugin.video.crackle/main.py", line 42, in <module>

get_stream(media_id)

File "/storage/.kodi/addons/plugin.video.crackle/resources/lib/globals.py", line 158, in get_stream

if not is_helper.check_inputstream():

File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 430, in check_inputstream

return self._check_drm()

File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 385, in _check_drm

return self.install_widevine()

File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after

self.cleanup()

File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 360, in cleanup

remove_tree(ia_cdm_path())

File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 331, in remove_tree

rmtree(compat_path(path))

File "/usr/lib/python3.8/shutil.py", line 718, in rmtree

File "/usr/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd

File "/usr/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd

File "/usr/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd

OSError: [Errno 30] Read-only file system: 'peripheral.joystick.so'

-->End of Python script error report<--

of course i tried uninstalling and re-installed inputstreamhelper

Please let me know if you have any ideas

![20220821_000046](https://user-images.githubusercontent.com/99011433/185768167-a1c7eba5-9d1b-4b93-800c-c580a6e7584d.jpg)
![IMG_20220821_004641](https://user-images.githubusercontent.com/99011433/185768169-3e9f5a96-bcaa-4ef8-84db-6cb9238b4a66.jpg)
s

**Comment by horstle** [comment]
Is it possible you restored a kodi backup from an Android device? I just read about somebody with the same issue who had tried to restore a backup from an Amazon Fire TV device to LibreELEC on an RPi. That won't work!

**Comment by Biomecanoid** [comment]
> Is it possible you restored a kodi backup from an Android device? I just read about somebody with the same issue who had tried to restore a backup from an Amazon Fire TV device to LibreELEC on an RPi. That won't work!

Thank you for the quick reply. I did not restore anything. I am running Libreelec on a mini x86 computer next to the TV nothing to do with Android or RPi.  Any other ideas  ?

**Comment by horstle** [comment]
Inputstreamhelper reads that from inputstream.adaptives settings. Something apparently changed the decrypter path there, but I wonder what/how.

**Comment by Biomecanoid** [comment]
> Inputstreamhelper reads that from inputstream.adaptives settings. Something apparently changed the decrypter path there, but I wonder what/how.

ΟΚ understood,  how do I change it manually what config file should I edit ?

**Comment by horstle** [comment]
You can change that from the GUI. Just go to the inpustream.adaptive settings.

**Comment by Biomecanoid** [comment]
> You can change that from the GUI. Just go to the inpustream.adaptive settings.

I already searched the GUI and I don't have "/usr/lib/kodi/addons" anywhere in the GUI

**Comment by horstle** [comment]
What does it say at "Decrypter path"?

**Comment by Biomecanoid** [comment]
> What does it say at "Decrypter path"?
it says special://home/cdm which is correct

I fixed it now. All i had to do is hit defaults both at inputstreamhelper and inputstream adaptive and then select restore Widevine CDM library - (Re)installed Widevine CDM library would not work

This was a weird issue, all GUI configuration all fine because I could compare it with my working box.  If I wanted to edit the config files manually which config is responsible ? 

Thank you for your help

**Comment by horstle** [comment]
That would be the inputstream.adaptive config. It should usually be in `/storage/.kodi/userdata/addon_data/inputstream.adaptive`, but I'm not sure. We're using a Kodi method to read the setting.

Since you fixed it, can this issue be closed?

**Comment by Biomecanoid** [comment]
Yes you can close the issue thank you for you help :)
