### ISSUE TITLE
Error -3 while decompressing data: invalid stored block lengths

### ISSUE THREAD

**Issue by vanMacG** [emilsvennesson/script.module.inputstreamhelper#523]
InputStream Helper Information:
Kodi Version: 19.4
InputStream Helper Version: 0.5.10+matrix.1
InputStream Adaptive Version: 19.0.7.1
Widevine CDM Version: 4.10.2449.0 from Chrome OS Image BOB Version 14989.107.0

When starting a movie in Netflix, there is a pop-up informing a new Widevine version is available. After the download, during extraction there comes the following error:
```
The operation has been cancelled.
InputStream Helper has generated an internal error:
Error -3 while decompressing data: invalid stored block lengths
```

Log:
```
2022-10-28 17:14:22.519 T:989   WARNING <general>: [script.module.inputstreamhelper] There is an update available for Chrome OS
2022-10-28 17:14:22.522 T:908      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-10-28 17:14:26.551 T:989   WARNING <general>: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.
2022-10-28 17:14:33.739 T:989      INFO <general>: Skipped 1 duplicate messages..
2022-10-28 17:14:33.739 T:989   WARNING <general>: [script.module.inputstreamhelper] Downloading ChromeOS image for Widevine: BOB (15054.98.0)
2022-10-28 17:14:33.939 T:908      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-10-28 17:20:39.818 T:989     ERROR <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 104, in get_inputstream_listitem
                                                       inputstream_ready = is_helper.check_inputstream()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 430, in check_inputstream
                                                       return self._check_drm()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 382, in _check_drm
                                                       return self._check_widevine()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 353, in _check_widevine
                                                       self._update_widevine()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 324, in _update_widevine
                                                       self.install_widevine()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 220, in install_widevine
                                                       result = install_widevine_arm(backup_path())
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 96, in install_widevine_arm
                                                       extracted = dl_extract_widevine(url, backup_path, arm_device)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 122, in dl_extract_widevine
                                                       progress = extract_widevine(backup_path, image_path, image_version)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 140, in extract_widevine
                                                       extracted = ChromeOSImage(image_path, progress=progress).extract_file(
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py", line 374, in extract_file
                                                       dir_dict = self.find_file(filename)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py", line 90, in find_file
                                                       inode_dict = self._inode_table(self._calc_inode_pos(dentries[dir_name]["inode"]))
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py", line 207, in _inode_table
                                                       self.seek_stream(inode_pos)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm_chromeos.py", line 274, in seek_stream
                                                       self.bstream[0].seek(seek_pos)
                                                     File "/usr/lib/python3.8/zipfile.py", line 1102, in seek
                                                     File "/usr/lib/python3.8/zipfile.py", line 940, in read
                                                     File "/usr/lib/python3.8/zipfile.py", line 1016, in _read1
                                                   zlib.error: Error -3 while decompressing data: invalid stored block lengths

2022-10-28 17:20:39.872 T:908      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
```

**Comment by vanMacG** [comment]
I was able to solve the issue by deleting the temp-folder (`/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/`). After that the (re)install ran without errors and widevine is now the newer version (4.10.2557.0).
