### ISSUE TITLE
Error on Kodi 20 nexus

### ISSUE THREAD

**Issue by enigma131** [emilsvennesson/script.module.inputstreamhelper#528]
Some channels are not playing on Nexus with Cathchup tv and more plugin.
This one is using inputstream helper, and for some channels it need updating the module and I get errors:
2023-01-25 17:25:59.530 T:383764   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: '/home/toto/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/4.10.2557.0-linux-x64.zip'
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                       widevine_install()
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 44, in widevine_install
                                                       Helper('mpd', drm='widevine').install_widevine()
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 214, in install_widevine
                                                       if not widevine_eula():
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 47, in widevine_eula
                                                       with ZipFile(compat_path(store('download_path'))) as archive:
                                                     File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
                                                       self.fp = io.open(file, filemode)
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/home/toto/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/4.10.2557.0-linux-x64.zip'
                                                   -->End of Python script error report<--
                                                   
2023-01-25 17:26:01.069 T:383766 warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/toto/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.

A possiblity to correct this ? (the version is tagged 0.5.10 Matrix 1 and not Nexus)

The module is working on Android with Nexus

**Comment by horstle** [comment]
Could you provide a debug log of a failed update?

**Comment by enigma131** [comment]
Error seems located on inputstream.adaptive , see at end https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1061

Helper is tagged as matrix, is it normal on Nexus ?
log :
https://paste.kodi.tv/ayaseqojul.kodi

**Comment by horstle** [comment]
> Helper is tagged as matrix, is it normal on Nexus ?

Yes, the Matrix version should work on Nexus.

**Comment by horstle** [comment]
Closing, since this was not an inputstreamhelper issue
