### ISSUE TITLE
Error at extracting

### ISSUE THREAD

**Issue by Shreyas-Alse** [emilsvennesson/script.module.inputstreamhelper#551]
I installed amazon VOD on kodi and attempted to play a video. Then it prompted me to install widevine. But when it extracts the file, it terminates and displays error. It leaves no log whatsoever. Can you help?

**Comment by horstle** [comment]
There definitely is a log file, but probably no debug log. Please enable debug logging, retry the installation and upload the debug log as explained here: https://kodi.wiki/view/Log_file

**Comment by Shreyas-Alse** [comment]
Ok I will do it. U will be able to help right?

**Comment by horstle** [comment]
If the error lies in inputstreamhelper, I'm sure I'll be able to fix it.

**Comment by Shreyas-Alse** [comment]
https://paste.kodi.tv/cikoyinaco.kodi
LOg

**Comment by Shreyas-Alse** [comment]
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error>
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'zlib.error'>
                                                   Error Contents: Error -3 while decompressing data: invalid code lengths set
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", lin>
                                                       widevine_install(choose_version=params[2])
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", lin>
                                                       Helper('mpd', drm='widevine').install_widevine(choose_version=choose_version)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py">
                                                       result = func(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py">
                                                       result = install_widevine_arm(backup_path())
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm>
                                                       extracted = dl_extract_widevine(url, backup_path, arm_device)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm>
                                                       progress = extract_widevine(backup_path, image_path, image_version)
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm>
                                                       extracted = ChromeOSImage(image_path, progress=progress).extract_file(
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm>
                                                       self.sb_dict = self._superblock()
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm>
                                                       self.seek_stream(self.part_offset + 1024)  # superblock starts after 1024 byte
                                                     File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm>
                                                       self.bstream[0].seek(seek_pos)
                                                     File "/usr/lib/python3.8/zipfile.py", line 1102, in seek
                                                     File "/usr/lib/python3.8/zipfile.py", line 940, in read
                                                     File "/usr/lib/python3.8/zipfile.py", line 1016, in _read1
                                                   zlib.error: Error -3 while decompressing data: invalid code lengths set
                                                   -->End of Python script error report<--

**Comment by Shreyas-Alse** [comment]
I sent the log.. plz help..

**Comment by horstle** [comment]
As mentioned in the link: Provide FULL Logs only. No Partial logs or snippets.

This code snippet is useless.

**Comment by Shreyas-Alse** [comment]
Ok, I will do that.

**Comment by Shreyas-Alse** [comment]
How can i copy the whole 3000 line log from ssh?
It doesnt copy ..

**Comment by horstle** [comment]
Maybe you could copy the file with scp?

**Comment by Shreyas-Alse** [comment]
ok..
https://paste.kodi.tv/uporufapeb.kodi

**Comment by Shreyas-Alse** [comment]
how can i do it, it doesnt go back from special folder. Can u plz help
me....

**Comment by Shreyas-Alse** [comment]
its a 16gb card..

**Comment by horstle** [comment]
If you have a keyboard, just press backspace.

**Comment by horstle** [comment]
The size of the card doesn't matter, if its broken.

**Comment by Shreyas-Alse** [comment]
Ok, thanks. I will try..

**Comment by Shreyas-Alse** [comment]
It worked as I installed slyguy input stream wrapper thanks a lot
