### ISSUE TITLE
Cannot link libraries on Archlinux due to missing permissions

### ISSUE THREAD

**Issue by MaxMatti** [emilsvennesson/script.module.inputstreamhelper#56]
Steps to reproduce:
Install Amazon VOD Add-On
Enable Adaptive Inputstream Add-On in Settings
In Amazon VOD Add-On: Login, start watching something

What happens:
Install Widevine popup appears, tries to install Widevine, fails after a while
What should happen:
After Widevine installation an error pops up, video is not played.

Ways to debug:
I modified the file `~/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py` by adding the following before line 692:

    self._log("addon: " + cdm_path_addon)
    self._log("stream: " + cdm_path_inputstream)
 
And then tried the whole thing again with logging enabled, leading to this log output:

    2019-05-20 11:26:23.733 T:139662384420608   DEBUG: [script.module.inputstreamhelper-0.3.4]: [install_cdm] found file: libwidevinecdm.so
    2019-05-20 11:26:23.734 T:139662384420608   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
    2019-05-20 11:26:23.734 T:139662384420608   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values
    2019-05-20 11:26:23.751 T:139662384420608   DEBUG: [script.module.inputstreamhelper-0.3.4]: addon: /home/max/.kodi/userdata/addon_data/script.module.inputstreamhelper/c
    dm/libwidevinecdm.so
    2019-05-20 11:26:23.751 T:139662384420608   DEBUG: [script.module.inputstreamhelper-0.3.4]: stream: /usr/lib/kodi/addons/inputstream.adaptive/libwidevinecdm.so
    2019-05-20 11:26:23.754 T:139662384420608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.OSError'>
                                                Error Contents: [Errno 13] Permission denied
                                                Traceback (most recent call last):
                                                  File "/home/max/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                    EntryPoint()
                                                  File "/home/max/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 74, in EntryPoint
                                                    PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('s
    elbitrate', '0')))
                                                  File "/home/max/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 462, in PlayVideo
                                                    playable = _IStreamPlayback(asin, name, trailer, isAdult, extern)
                                                  File "/home/max/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 344, in _IStreamPlayback
                                                    if not inputstream_helper.check_inputstream():
                                                  File "/home/max/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 778, in check_inputstream
                                                    return self._check_drm()
                                                  File "/home/max/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 749, in _check_drm
                                                    return self._install_widevine()
                                                  File "/home/max/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 550, in _install_widevine
                                                    return self._install_widevine_x86()
                                                  File "/home/max/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 458, in _install_widevine_x86
                                                    self._install_cdm()
                                                  File "/home/max/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 694, in _install_cdm
                                                    os.symlink(cdm_path_addon, cdm_path_inputstream)
                                                OSError: [Errno 13] Permission denied
                                                -->End of Python script error report<--

# Fix
I ran this command to fix it:

    sudo chmod 777 /usr/lib/kodi/addons/inputstream.adaptive/

However I had to find out all of this by myself, would you mind putting in a check that handles this type of error and displays a more informative error message to the user?

**Comment by MaxMatti** [comment]
I forgot to mention: the "what happens" section should include that I pressed "ok" and "accept" a few times in the "install Widevine" popup(s).

**Comment by dagwieers** [comment]
From a security-point of view, this is not a good solution.
But there's also no reason why **inputstreamhelper** is writing to that directory.
The symlink is normally created in: *~/.kodi/cdm/*

What environment is this? OS? Kodi?

**Comment by dagwieers** [comment]
So if you have more information related to this issue, we would still like to know.
We would also like to know if this issue still happens with the current master branch.
In any case, if you have new information or test results, please reopen this issue, or report them here.
Thanks!

**Comment by MaxMatti** [comment]
> What environment is this? OS version? Kodi?
> Have you reported this to the Archlinux Kodi maintainer?

Archlinux doesn't have versions, as for the package version it was the one that was distributed via the repos at that date. I haven't thought that this might be a packaging issue, I'll contact the maintainer.
