### ISSUE TITLE
The widevine library does not install.

### ISSUE THREAD

**Issue by 68foxboris** [emilsvennesson/script.module.inputstreamhelper#563]
I assembled and installed the plugin in Kodi 21.0.Python 3.12.3.
SRCREV = "e5bc154525bcf1dea11138c30f602f441a361d79"
When trying to update the WIDEVINE library, the error is:

2024-05-19 16:19:37.077 T:9202  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/root/.kodi/cdm/'.
2024-05-19 16:19:37.082 T:9202    error <general>: [script.module.inputstreamhelper] Widevine CDM is not installed.
2024-05-19 16:19:37.089 T:9202  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/root/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.
2024-05-19 16:19:37.130 T:9202    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'distutils'
                                                   Traceback (most recent call last):
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 356, in parse_version
                                                       from packaging.version import parse
                                                   ModuleNotFoundError: No module named 'packaging'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 15, in run
                                                       widevine_install(choose_version=params[2])
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 48, in widevine_install
                                                       Helper('mpd', drm='widevine').install_widevine(choose_version=choose_version)
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 219, in install_widevine
                                                       if not self._supports_widevine():
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 163, in _supports_widevine
                                                       if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/root/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 359, in parse_version
                                                       from distutils.version import LooseVersion  # pylint: disable=deprecated-module
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   ModuleNotFoundError: No module named 'distutils'
                                                   -->End of Python script error report<--

**Comment by horstle** [comment]
Please install the following zip and try again

[script.module.inputstreamhelper-0.6.1-master-e5bc154.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/15380289/script.module.inputstreamhelper-0.6.1-master-e5bc154.zip)

**Comment by 68foxboris** [comment]
It works. Is the plugin not building correctly for me or did you change something?
![screenshot_20240522220630](https://github.com/emilsvennesson/script.module.inputstreamhelper/assets/17230642/487aa843-9e4b-4833-a180-5af032388011)
Here is my assembly recipe.
[kodi-addon-inputstreamhelper.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/15410901/kodi-addon-inputstreamhelper.zip)

**Comment by horstle** [comment]
I didn't change anything. I built the zip with `make zip`. See the Makefile.

I have no experience with yocto build recipes, but it seems your KODIADDONDIR is wrong. there is a dot missing before kodi, i.e. `${datadir}/.kodi/addons`

The sed command is no longer necessary. Other than that I guess it should be fine.

**Comment by horstle** [comment]
Can this issue be closed?
