### ISSUE TITLE
Crash on Python 3.12.3 [version 0.6.1+matrix.1]

### ISSUE THREAD

**Issue by stsichler** [emilsvennesson/script.module.inputstreamhelper#566]
Hi,

I just installed a fresh Kodi 20.5 on an Ubuntu noble arm64.
As soon as I installed inputstreamhelper, Kodi crashes when clicking on the Addon.
I'm not exactly sure what is causing this, but gdb gives me this error and callstack: 
<code>
Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
Python runtime state: initialized

Thread 0x0000007f4efde4e0 (most recent call first):
  <no Python frame>

Thread 1 "kodi.bin" received signal SIGABRT, Aborted.
Download failed: Invalid argument.  Continuing without source file ./nptl/./nptl/pthread_kill.c.
__pthread_kill_implementation (threadid=548324421664, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: No such file or directory
(gdb) bt
#0  __pthread_kill_implementation (threadid=548324421664, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x0000007fa4f47690 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x0000007fa4efcb3c in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000007fa4ee7e00 in __GI_abort () at ./stdlib/abort.c:79
#4  0x0000007faa15f18c in ?? () from /lib/aarch64-linux-gnu/libpython3.12.so.1.0
#5  0x0000007faa15f210 in _Py_FatalErrorFunc () from /lib/aarch64-linux-gnu/libpython3.12.so.1.0
#6  0x0000007faa142168 in PyImport_AppendInittab () from /lib/aarch64-linux-gnu/libpython3.12.so.1.0

</code>

**Comment by stsichler** [comment]
this seems related to https://github.com/xbmc/xbmc/issues/24069 and these guys obviously decided to ignore it for Nexus.

**Comment by garbear** [comment]
Unfortunately our apt repo maintainer stepped down. We know it sucks but the only way to get a supported version of Kodi on Ubuntu now is flatpak or compile from source, both of which are on Omega. If the bug can be reproduced in Omega we're happy to fix it.

It's a manpower issue, so if we get a volunteer to handle apt packaging, we'll bring the repos back.
