### ISSUE TITLE
Inputstream helper started to crash, cannot download winedivine now

### ISSUE THREAD

**Issue by Elkropac** [emilsvennesson/script.module.inputstreamhelper#568]
Kodi started to have problem today. 
System is Debian Trixie, kodi version 2:21.1+dfsg-5 , inputstream helper is v0.6.1+matrix.1.

```
2024-09-17 15:50:26.127 T:2128  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/prehravac/.kodi/cdm/'.
2024-09-17 15:50:26.128 T:2128    error <general>: [script.module.inputstreamhelper] Widevine CDM is not installed.
2024-09-17 15:50:26.131 T:2128  warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/prehravac/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.
2024-09-17 15:50:29.347 T:2128    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 15, in run
                                                       widevine_install(choose_version=params[2])
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 48, in widevine_install
                                                       Helper('mpd', drm='widevine').install_widevine(choose_version=choose_version)
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                       if not widevine_eula():
                                                              ^^^^^^^^^^^^^^^
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 32, in widevine_eula
                                                       cdm_version = latest_widevine_available_from_repo().get('version')
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/prehravac/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 199, in latest_widevine_available_from_repo
                                                       if parse_version(cdm['version']) > parse_version(latest['version']):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   -->End of Python script error report<--
```

These packages were updated today in system (there is some python stuff, but i don't know if it's related)
```
Start-Date: 2024-09-17  12:36:23
Commandline: /usr/bin/unattended-upgrade
Upgrade: python3-charset-normalizer:amd64 (3.3.2-2, 3.3.2-3)
End-Date: 2024-09-17  12:36:24

Start-Date: 2024-09-17  12:36:25
Commandline: /usr/bin/unattended-upgrade
Upgrade: udev:amd64 (256.5-1, 256.6-1), libnss-myhostname:amd64 (256.5-1, 256.6-1), systemd-timesyncd:amd64 (256.5-1, 256.6-1), libpam-systemd:amd64 (256.5-1, 256.6-1), libsystemd0:amd64 (256.5-1, 256.6-1), libnss-systemd:amd64 (256.5-1, 256.6-1), systemd:amd64 (256.5-1, 256.6-1), libudev1:amd64 (256.5-1, 256.6-1), systemd-cryptsetup:amd64 (256.5-1, 256.6-1), systemd-resolved:amd6
4 (256.5-1, 256.6-1), libnss-resolve:amd64 (256.5-1, 256.6-1), libsystemd-shared:amd64 (256.5-1, 256.6-1), systemd-sysv:amd64 (256.5-1, 256.6-1)
End-Date: 2024-09-17  12:36:47

Start-Date: 2024-09-17  12:36:48
Commandline: /usr/bin/unattended-upgrade
Upgrade: gstreamer1.0-gl:amd64 (1.24.7-2, 1.24.7-4), libgstreamer-gl1.0-0:amd64 (1.24.7-2, 1.24.7-4), gstreamer1.0-x:amd64 (1.24.7-2, 1.24.7-4), gstreamer1.0-plugins-base:amd64 (1.24.7-2, 1.24.7-4), libgstreamer-plugins-base1.0-0:amd64 (1.24.7-2, 1.24.7-4)
End-Date: 2024-09-17  12:36:49

Start-Date: 2024-09-17  12:36:51
Commandline: /usr/bin/unattended-upgrade
Install: python3-inflect:amd64 (7.3.1-1, automatic), python3-autocommand:amd64 (2.2.2-3, automatic), python3-jaraco.functools:amd64 (4.0.2-1, automatic), python3-typing-extensions:amd64 (4.12.2-2, automatic), python3-jaraco.context:amd64 (6.0.0-1, automatic), python3-more-itertools:amd64 (10.4.0-1, automatic), python3-typeguard:amd64 (4.3.0-1, automatic), python3-zipp:amd64 (3.20.
1-1, automatic)
Upgrade: python3-pkg-resources:amd64 (70.3.0-2, 74.1.2-2), python3-setuptools:amd64 (70.3.0-2, 74.1.2-2)
End-Date: 2024-09-17  12:36:57

Start-Date: 2024-09-17  12:36:58
Commandline: /usr/bin/unattended-upgrade
Upgrade: libnet-domain-tld-perl:amd64 (1.75-3, 1.75-4)
End-Date: 2024-09-17  12:37:00

Start-Date: 2024-09-17  12:37:01
Commandline: /usr/bin/unattended-upgrade
Upgrade: lintian:amd64 (2.118.1, 2.118.2)
End-Date: 2024-09-17  12:37:08
```

**Comment by Elkropac** [comment]
I have downgraded `python3-setuptools` and `python3-pkg-resources` back to version `70.3.0-2` from `74.1.2-2` and it fixed it for me

**Comment by emilsvennesson** [comment]
Hi! Can you confirm if https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/571 solves it?
