### ISSUE TITLE
TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'

### ISSUE THREAD

**Issue by Paco8** [emilsvennesson/script.module.inputstreamhelper#570]
The following error happens on Linux (flatpak version) using inputstreamhelper 0.6.1:

```
  File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.amazon-test/resources/lib/playback.py", line 471, in PlayVideo
    suc = _IStreamPlayback(asin, name, streamtype, isAdult, extern)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.var/app/tv.kodi.Kodi/data/addons/plugin.video.amazon-test/resources/lib/playback.py", line 342, in _IStreamPlayback
    if not inputstream_helper.check_inputstream():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 420, in check_inputstream
    if self.drm == 'widevine' and not self._supports_widevine():
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 163, in _supports_widevine
    if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
-->End of Python script error report<--
```

**Comment by DjDiabolik** [comment]
@emilsvennesson same errors appears about two hours ago when i try to use my DAZN account for watch Juventus Napoli (whit my valid login).
I have report the error here on addons fork:
https://github.com/Maven85/plugin.video.dazn/commit/fb45f98ec7e16299cb80aaac4aa27f52077eec28#commitcomment-147020701

but i have tryed to (Re)Install the Widevide CDM this errors appears:
`2024-09-21 20:12:23.637 T:894745 warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/diabolik/.var/app/tv.kodi.Kodi/data/userdata/addon_data/script.module.inputstreamhelper/temp/'.
2024-09-21 20:12:23.769 T:894745   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 15, in run
                                                       widevine_install(choose_version=params[2])
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 48, in widevine_install
                                                       Helper('mpd', drm='widevine').install_widevine(choose_version=choose_version)
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 219, in install_widevine
                                                       if not self._supports_widevine():
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/diabolik/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 163, in _supports_widevine
                                                       if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   -->End of Python script error report<--
                                                   
2024-09-21 20:12:29.210 T:21       info <general>: CActiveAESink::OpenSink - initialize sink
2024-09-21 20:12:29.210 T:21       info <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2024-09-21 20:12:29.217 T:21       info <general>: CAESinkALSA::Initialize - Opened device "default"`

**Comment by DjDiabolik** [comment]
@Paco8 if you want to try to back to use your addons try to disable the "inputstream helper" from setting in the debug section.

**Comment by emilsvennesson** [comment]
Can you test if https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/571 solves it?

**Comment by DjDiabolik** [comment]
> Can you test if #571 solves it?

How i can install this ? I can download the zip manually from branch and install manually ?

**Comment by Paco8** [comment]
> Can you test if #571 solves it?

Yes, it fixes the problem for  me.

**Comment by DjDiabolik** [comment]
> > Can you test if #571 solves it?
> 
> Yes, it fixes the problem for me.

How you have installed that ?

**Comment by Paco8** [comment]
I downloaded this:
https://github.com/emilsvennesson/script.module.inputstreamhelper/tree/fix-version-parsing

**Comment by DjDiabolik** [comment]
> I downloaded this: https://github.com/emilsvennesson/script.module.inputstreamhelper/tree/fix-version-parsing

simply download as zip and install on kodi ? or it's need to do other ?

**Comment by Paco8** [comment]
Yes, download as zip and install.

**Comment by DjDiabolik** [comment]
> Yes, download as zip and install.

@Paco8 i thinks at right now also the master branch as the #571 applied... try to install this :)

**Comment by DjDiabolik** [comment]
@emilsvennesson strange issue.. i have installed the master branch zip for resolve the issue.... now kodi say to me it's exist an update for this addons and suggest to me to upgrade to, apparently, same version from kodi official repository.

It's a newest 0.6.1 has been released recently ?

**Comment by emilsvennesson** [comment]
Fixed on 0.7.0.

**Comment by DjDiabolik** [comment]
@emilsvennesson in the meantime i have understand because, after the installation of master branch zip manually, my kodi keep to continue to found an update:
Current 0.6.1 on Kodi main repo it's "named 0.6.1+matrix.1"  if i remember. The master zip branch in addons.xml simply 0.6.1... for kodi the +matrix.1 it's an updated addons :)

Thanks for 0.7.0.... need to wait as been push on main kodi repo.
Or you have a your personal repo ?

**Comment by emilsvennesson** [comment]
@DjDiabolik It is awaiting approval in the Kodi repo, but you can download it from https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.7.0 in the meantime.

**Comment by DjDiabolik** [comment]
> @DjDiabolik It is awaiting approval in the Kodi repo, but you can download it from https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.7.0 in the meantime.

Exactly...That's the first thing I thought of too. Thanks for fixing this issue :)
